-- MySQL Script generated by MySQL Workbench
-- Wed Aug 23 00:13:39 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema t1moon$bonus_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `t1moon$bonus_db` ;

-- -----------------------------------------------------
-- Schema t1moon$bonus_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `t1moon$bonus_db` DEFAULT CHARACTER SET utf8 ;
USE `t1moon$bonus_db` ;

-- -----------------------------------------------------
-- Table `t1moon$bonus_db`.`usertype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `t1moon$bonus_db`.`usertype` ;

CREATE TABLE IF NOT EXISTS `t1moon$bonus_db`.`usertype` (
  `usertype_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`usertype_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `t1moon$bonus_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `t1moon$bonus_db`.`user` ;

CREATE TABLE IF NOT EXISTS `t1moon$bonus_db`.`user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `userType` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  INDEX `fk_type_idx` (`userType` ASC),
  CONSTRAINT `fk_usertype`
    FOREIGN KEY (`userType`)
    REFERENCES `t1moon$bonus_db`.`usertype` (`usertype_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `t1moon$bonus_db`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `t1moon$bonus_db`.`client` ;

CREATE TABLE IF NOT EXISTS `t1moon$bonus_db`.`client` (
  `client_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `identificator` VARCHAR(45) NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`client_id`),
  INDEX `fk_user_id_idx` (`user_id` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `t1moon$bonus_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `t1moon$bonus_db`.`loaylityscheme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `t1moon$bonus_db`.`loaylityscheme` ;

CREATE TABLE IF NOT EXISTS `t1moon$bonus_db`.`loaylityscheme` (
  `loaylityscheme_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`loaylityscheme_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `t1moon$bonus_db`.`job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `t1moon$bonus_db`.`job` ;

CREATE TABLE IF NOT EXISTS `t1moon$bonus_db`.`job` (
  `job_id` INT(11) NOT NULL,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`job_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `t1moon$bonus_db`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `t1moon$bonus_db`.`staff` ;

CREATE TABLE IF NOT EXISTS `t1moon$bonus_db`.`staff` (
  `staff_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `surname` VARCHAR(45) NULL DEFAULT NULL,
  `age` INT(11) NULL DEFAULT NULL,
  `jobTitle` INT(11) NOT NULL,
  PRIMARY KEY (`staff_id`),
  INDEX `fk_job_title_idx` (`jobTitle` ASC),
  CONSTRAINT `jobTitle_fk`
    FOREIGN KEY (`jobTitle`)
    REFERENCES `t1moon$bonus_db`.`job` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `t1moon$bonus_db`.`host`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `t1moon$bonus_db`.`host` ;

CREATE TABLE IF NOT EXISTS `t1moon$bonus_db`.`host` (
  `host_id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `address` VARCHAR(500) NULL DEFAULT NULL,
  `time_open` INT(11) NULL DEFAULT NULL,
  `time_close` INT(11) NULL DEFAULT NULL,
  `profile_image` VARCHAR(500) NULL DEFAULT NULL,
  `add_percent` INT(11) NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  `staff_id` INT(11) NULL DEFAULT NULL,
  `loyalityScheme` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`host_id`),
  INDEX `fk_user_id_idx` (`user_id` ASC),
  INDEX `fk_staff_id_idx` (`staff_id` ASC),
  INDEX `fk_loyalityscheme_idx` (`loyalityScheme` ASC),
  CONSTRAINT `fk_loyalityscheme`
    FOREIGN KEY (`loyalityScheme`)
    REFERENCES `t1moon$bonus_db`.`loaylityscheme` (`loaylityscheme_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_staff_id`
    FOREIGN KEY (`staff_id`)
    REFERENCES `t1moon$bonus_db`.`staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `t1moon$bonus_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `t1moon$bonus_db`.`score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `t1moon$bonus_db`.`score` ;

CREATE TABLE IF NOT EXISTS `t1moon$bonus_db`.`score` (
  `host_id` INT(11) NOT NULL,
  `client_id` INT(11) NOT NULL,
  `amount` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`host_id`, `client_id`),
  INDEX `client_fk_idx` (`client_id` ASC),
  CONSTRAINT `client_fk`
    FOREIGN KEY (`client_id`)
    REFERENCES `t1moon$bonus_db`.`client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `host_fk`
    FOREIGN KEY (`host_id`)
    REFERENCES `t1moon$bonus_db`.`host` (`host_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `t1moon$bonus_db`.`transactiontype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `t1moon$bonus_db`.`transactiontype` ;

CREATE TABLE IF NOT EXISTS `t1moon$bonus_db`.`transactiontype` (
  `transactiontype_id` INT(11) NOT NULL,
  `transactionTypeName` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`transactiontype_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `t1moon$bonus_db`.`transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `t1moon$bonus_db`.`transactions` ;

CREATE TABLE IF NOT EXISTS `t1moon$bonus_db`.`transactions` (
  `host_id` INT(11) NOT NULL,
  `client_id` INT(11) NOT NULL,
  `transactionTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `type_id` INT(11) NOT NULL,
  `amount` INT(11) NOT NULL,
  PRIMARY KEY (`host_id`, `client_id`, `transactionTime`),
  INDEX `fk_client_id_idx` (`client_id` ASC),
  INDEX `fk_type_idx` (`type_id` ASC),
  CONSTRAINT `fk_client_id`
    FOREIGN KEY (`client_id`)
    REFERENCES `t1moon$bonus_db`.`client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_host_id`
    FOREIGN KEY (`host_id`)
    REFERENCES `t1moon$bonus_db`.`host` (`host_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_type`
    FOREIGN KEY (`type_id`)
    REFERENCES `t1moon$bonus_db`.`transactiontype` (`transactiontype_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
